name: Build BridgeSSH

permissions:
  contents: write

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Electron app on Windows
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: npx electron-builder --win

      - name: Build Electron app on Linux
        if: matrix.os == 'ubuntu-latest'
        shell: bash
        run: npx electron-builder --linux

      - name: Build Electron app on macOS
        if: matrix.os == 'macos-latest'
        shell: bash
        run: npx electron-builder --mac

      - name: Set Tag Name
        id: tag_unix
        if: ${{ matrix.os != 'ubuntu-latest' && matrix.os != 'macos-latest' }}
        run: |
          DATE=$(date +%Y-%m-%d-%H-%M-%S)
          TAG="v1.0.0-$DATE"
          echo "tag_name=$TAG" >> $GITHUB_OUTPUT
          
      - name: Set Tag Name on Windows
        id: tag_windows
        shell: pwsh
        if: matrix.os == 'windows-latest'
        run: |
             $DATE = Get-Date -Format "yyyy-MM-dd-HH-mm-ss"
              $TAG = "v1.0.0-$DATE"
              echo "tag_name=$TAG" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

      - name: Create Git Tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ steps.tag.outputs.tag_name }}
          git push origin ${{ steps.tag.outputs.tag_name }}
        shell: bash

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.tag_unix }}${{ steps.tag.outputs.tag_windows }}
          release_name: ${{ steps.tag.outputs.tag_unix }}${{ steps.tag.outputs.tag_windows }}
          draft: false
          prerelease: false

      - name: Upload Artifacts to Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.tag_name }}
          files: dist/*
