name: Build BridgeSSH

permissions:
  contents: write

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  create_tag:
    runs-on: ubuntu-latest
    outputs:
      TAG_NAME: ${{ steps.generate_tag.outputs.TAG_NAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate Tag Name
        id: generate_tag
        shell: bash
        run: |
          DATE=$(date +%Y-%m-%d-%H-%M-%S)
          TAG="v1.0.1-$DATE"
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag $TAG
          git push origin $TAG
          echo "::set-output name=TAG_NAME::$TAG"

  build:
    needs: create_tag
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TAG_NAME: ${{ needs.create_tag.outputs.TAG_NAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Electron app on Windows
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: npx electron-builder --win --publish always

      - name: Build Electron app on Linux
        if: matrix.os == 'ubuntu-latest'
        shell: bash
        run: npx electron-builder --linux --publish always

      - name: Build Electron app on macOS
        if: matrix.os == 'macos-latest'
        shell: bash
        run: npx electron-builder --mac --publish always
